services:
    pbs-client:
        image: ghcr.io/coxde/pbs-client:latest@sha256:7e5f0ddabf48462ab47b626567ab94ef03c6cd7a059d51b07a76c79c8045dcaf
        # Adjust the container name and hostname to change the naming within the PBS server
        # backups, e.g. this would set ``host/pbs-client``.
        container_name: pbs-client
        hostname: pbs-client
        restart: unless-stopped
        env_file:
            - .env
        tmpfs:
            - /run:exec
        volumes:
            - type: tmpfs
              target: /tmp
              tmpfs:
                  size: 1073741824
            - ./container/pbsconfig/:/root/.config/proxmox-backup/
            # Note - if you want to restore backups make sure to change to read write below.
            # See the 'restore-backup' command inside the container.
            - ./container/backups/test1:/backups/test1:ro
            - ./container/backups/test2:/backups/test2:ro
            - ./container/backups/test3:/backups/test3:ro
            # If you want to provide bash hooks, you can mount volumes as below. See the .env.example
            # for more information.
            #- ./container/hooks/pre.d:/hooks/pre.d:ro
            #- ./container/hooks/post.d:/hooks/post.d:ro
