name: Build and Publish Container Image

on:
    push:
        branches: [main]
    schedule:
        - cron: "0 9 * * 6"
    workflow_dispatch:

jobs:
    build-and-push-image:
        name: Build Container image and publish multi-arch
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                  submodules: recursive

            - name: Force permissions fix
              run: sudo apt-get update && sudo apt-get install dos2unix -y && cd ./container && bash dos2unix.sh

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            - name: Login to Github Packages
              uses: docker/login-action@v4
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Get current date
              run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

            ###########################################################
            # Build AMD64 image (uses Containerfile)
            ###########################################################
            - name: Build AMD64 image
              run: |
                  docker buildx build \
                    --platform linux/amd64 \
                    -f ./Containerfile \
                    -t coxde/pbs-client:amd64-latest \
                    -t coxde/pbs-client:amd64-${DATE} \
                    -t ghcr.io/coxde/pbs-client:amd64-latest \
                    -t ghcr.io/coxde/pbs-client:amd64-${DATE} \
                    .

            ###########################################################
            # Build ARM64 debs
            ###########################################################
            - name: Build ARM64 packages
              run: |
                  docker buildx build \
                    -o proxmox-backup-arm64/packages \
                    --build-arg buildoptions="cross github client" \
                    --build-arg baseimage=debian:trixie-slim \
                    --platform linux/amd64 \
                    -f proxmox-backup-arm64/.github/Dockerfile.crosscompile-arm64 \
                    proxmox-backup-arm64

            ###########################################################
            # Build ARM64 image (uses Containerfile.arm64)
            ###########################################################
            - name: Build ARM64 image
              run: |
                  cp -r proxmox-backup-arm64/packages ./packages
                  docker buildx build \
                    --platform linux/arm64 \
                    -f ./Containerfile.arm64 \
                    -t coxde/pbs-client:arm64-latest \
                    -t coxde/pbs-client:arm64-${DATE} \
                    -t ghcr.io/coxde/pbs-client:arm64-latest \
                    -t ghcr.io/coxde/pbs-client:arm64-${DATE} \
                    .

            ###########################################################
            # Create multi-arch manifests
            ###########################################################
            - name: Create and push multi-arch manifest
              run: |
                  # GHCR latest
                  docker buildx imagetools create \
                    -t ghcr.io/coxde/pbs-client:latest \
                    ghcr.io/coxde/pbs-client:amd64-latest \
                    ghcr.io/coxde/pbs-client:arm64-latest

                  # GHCR dated
                  docker buildx imagetools create \
                    -t ghcr.io/coxde/pbs-client:${DATE} \
                    ghcr.io/coxde/pbs-client:amd64-${DATE} \
                    ghcr.io/coxde/pbs-client:arm64-${DATE}
