name: Build and Publish Image

on:
    push:
        branches:
            - "renovate/**"
    pull_request:
        branches:
            - "main"
        paths-ignore:
            - "**.md"
            - ".github/workflows/renovate.json5"
    schedule:
        - cron: "25 6 * * 0" # At 06:25 on every Sunday.
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-image-check:
        name: Build Image Check
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/renovate/') }}

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  submodules: recursive

            - name: Force permissions fix
              run: sudo apt-get update && sudo apt-get install dos2unix -y && cd ./container && bash dos2unix.sh

            - name: Set up QEMU
              uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

            - name: Build arm64 packages (ci check)
              run: |
                  docker buildx build \
                    -o proxmox-backup-arm64/packages \
                    --build-arg buildoptions="cross github client" \
                    --build-arg baseimage=debian:trixie-slim \
                    --platform linux/amd64 \
                    -f proxmox-backup-arm64/.github/Dockerfile.crosscompile-arm64 \
                    proxmox-backup-arm64

            - name: Build arm64 image (ci check)
              uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
              with:
                  context: .
                  file: ./Containerfile.arm64
                  platforms: linux/arm64
                  push: false

    build-and-push-image:
        name: Build and Push Image to Registry
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'pull_request' }}
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
              with:
                  submodules: recursive

            - name: Force permissions fix
              run: sudo apt-get update && sudo apt-get install dos2unix -y && cd ./container && bash dos2unix.sh

            - name: Login to Github registry
              uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

            - name: Build arm64 packages
              run: |
                  docker buildx build \
                    -o proxmox-backup-arm64/packages \
                    --build-arg buildoptions="cross github client" \
                    --build-arg baseimage=debian:trixie-slim \
                    --platform linux/amd64 \
                    -f proxmox-backup-arm64/.github/Dockerfile.crosscompile-arm64 \
                    proxmox-backup-arm64

            - name: Build amd64 image
              uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
              with:
                  context: .
                  file: ./Containerfile
                  platforms: linux/amd64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }}

            - name: Build arm64 image
              uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
              with:
                  context: .
                  file: ./Containerfile.arm64
                  platforms: linux/arm64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}

            - name: Create and push multi-arch manifest
              run: |
                  docker buildx imagetools create \
                    -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
                    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }} \
                    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}
