name: Build and Publish Image

on:
    pull_request:
        branches:
            - main
        paths-ignore:
            - "**.md"
            - ".github/workflows/renovate.json5"
    schedule:
        - cron: "25 6 * * 0" # At 06:25 on every Sunday.
    workflow_dispatch:

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
        name: Build and Push Image to Registry
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v7
              with:
                  submodules: recursive

            - name: Force permissions fix
              run: sudo apt-get update && sudo apt-get install dos2unix -y && cd ./container && bash dos2unix.sh

            - name: Login to Github registry
              uses: docker/login-action@v4
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4

            ######## Pull request check ########
            - name: Build arm64 packages (pr check)
              if: github.event_name == 'pull_request'
              run: |
                  docker buildx build \
                    -o proxmox-backup-arm64/packages \
                    --build-arg buildoptions="cross github client" \
                    --build-arg baseimage=debian:trixie-slim \
                    --platform linux/amd64 \
                    -f proxmox-backup-arm64/.github/Dockerfile.crosscompile-arm64 \
                    proxmox-backup-arm64

            - name: Build arm64 image (pr check)
              if: github.event_name == 'pull_request'
              uses: docker/build-push-action@v7
              with:
                  context: .
                  file: ./Containerfile.arm64
                  platforms: linux/arm64
                  push: false

            ######## Build images ########
            - name: Build amd64 image (from Containerfile)
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@v7
              with:
                  context: .
                  file: ./Containerfile
                  platforms: linux/amd64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }}

            - name: Build arm64 packages
              if: github.event_name != 'pull_request'
              run: |
                  docker buildx build \
                    -o proxmox-backup-arm64/packages \
                    --build-arg buildoptions="cross github client" \
                    --build-arg baseimage=debian:trixie-slim \
                    --platform linux/amd64 \
                    -f proxmox-backup-arm64/.github/Dockerfile.crosscompile-arm64 \
                    proxmox-backup-arm64

            - name: Build arm64 image (from Containerfile.arm64)
              if: github.event_name != 'pull_request'
              uses: docker/build-push-action@v7
              with:
                  context: .
                  file: ./Containerfile.arm64
                  platforms: linux/arm64
                  push: true
                  tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}

            - name: Create and push multi-arch manifest
              if: github.event_name != 'pull_request'
              run: |
                  docker buildx imagetools create \
                    -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
                    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:amd64-${{ github.sha }} \
                    ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:arm64-${{ github.sha }}
